log:
  level: warn
  production: true
  file: "/var/log/mosdns.log"

plugins:
  # 缓存优化
  - tag: "cache"
    type: cache
    args:
      size: 32768
      lazy_cache_ttl: 86400
      dump_file: "/var/db/mosdns.cache"
      dump_interval: 300

  # PTR 反向解析
  - tag: "reverse_lookup"
    type: reverse_lookup
    args:
      size: 5000
      ttl: 14400
      handle_ptr: true

  # 境外域名集
  - tag: "remote_domain_set"
    type: domain_set
    args:
      files:
        - "./domains/gfw.txt"
        - "./domains/proxy-list.txt"

  # 国内域名集
  - tag: "direct_domain_set"
    type: domain_set
    args:
      files:
        - "./domains/direct-list.txt"

  # 国内 IP 集
  - tag: "direct_ip"
    type: ip_set
    args:
      files:
        - "./ips/all_cn.txt"

  # 本地运营商 DNS（Unbound 或 ISP）
  - tag: "local_forward"
    type: forward
    args:
      upstreams:
        - tag: local_dns
          addr: "udp://114.114.114.114"  # 可换成你实际运营商 DNS

  # 🚀 远程 DNS（经 Clash 代理转发）
  - tag: "remote_forward"
    type: forward
    args:
      upstreams:
        - tag: google_doh
          addr: "https://dns.google/dns-query"
          socks5: "127.0.0.1:7891"
          idle_timeout: 10

        - tag: cloudflare_doh
          addr: "https://cloudflare-dns.com/dns-query"
          socks5: "127.0.0.1:7891"
          idle_timeout: 10

        - tag: quad9_doh
          addr: "https://dns.quad9.net/dns-query"
          socks5: "127.0.0.1:7891"
          idle_timeout: 10

        - tag: unbound_dns
          addr: "udp://127.0.0.1:5355"
          idle_timeout: 10

  # 国内 DNS（DoT）
  - tag: "domestic_forward"
    type: forward
    args:
      upstreams:
        - tag: ali_dot
          addr: "tls://223.5.5.5"
          idle_timeout: 10
        - tag: tencent_dot
          addr: "tls://119.29.29.29"
          idle_timeout: 10

  # TTL 控制
  - tag: "ttl_sequence"
    type: sequence
    args:
      - exec: ttl 600-86400
      - exec: accept

  # 国内解析流程
  - tag: "domestic_sequence"
    type: sequence
    args:
      - exec: $domestic_forward
      - exec: goto ttl_sequence

  # 国外解析流程
  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: $remote_forward
      - matches: "resp_ip $direct_ip"
        exec: $domestic_forward
      - exec: goto ttl_sequence

  # 智能 fallback
  - tag: "fallback"
    type: fallback
    args:
      primary: remote_sequence
      secondary: domestic_sequence
      threshold: 300
      always_standby: true

  # 主解析流程
  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $cache
      - matches: has_resp
        exec: accept
      - exec: $reverse_lookup
      - matches: has_resp
        exec: accept
      - matches: "qname $remote_domain_set"
        exec: goto remote_sequence
      - matches: "qname $direct_domain_set"
        exec: goto domestic_sequence
      - exec: $fallback

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :5335

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: :5335
